# -*- coding: utf-8 -*-
"""Exercicios_loop_While.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DfQuWMz-d6lzcOhWog12csT9Zml_DJfj

1. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem
caso o valor seja inválido e continue pedindo até que o usuário informe um valor
válido
"""

nota = float(input('Digite uma nota entre zero e dez: '))

while nota > 10 or nota <0:
  nota = float (input('Digite uma nota válida! '))

print('Parabéns, voce digitou a nota corretamente!')

""" 2. Faça um programa que calcule o mostre a média aritmética de N notas."""

nota1 = float((input('Digite a primeira nota: ')))

while nota1 < 0 or nota1 >10 :
  nota1 = float(input('Digite uma primeira nota válida: '))

nota2 = float((input('Digite a segunda nota: ')))

while nota2 < 0 or nota2 >10:
  nota2 = float(input('Digite uma segunda nota válida: '))

nota3 = float((input('Digite a terceira nota: ')))

while nota3 <0 or nota3 >10:
  nota3 = float(input('Digite uma terceira nota válida: '))

media = (nota1+nota2+nota3)/3

print('Com base nas notas digitadas por voce, obtemos {:.1f} como média!'.format(media))

"""3. Faça um programa que leia um nome de usuário e a sua senha e não aceite a
senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a
pedir as informações.

"""

usuario = (input('Digite um nome de usuário: '))
senha = (input('Informe uma senha: '))

while usuario == senha:
  senha = (input('A senha fornecida náo pode ser idêntica ao usuário, digite uma senha válida: '))

print('Parabéns login criado com sucesso!')

"""4. Um funcionário de uma empresa recebe aumento salarial anualmente.
Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$1.000,00;

Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de
1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
percentual do ano anterior.

Faça um programa que determine o salário atual desse
funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
salário inicial do funcionár

"""

salario = float(input('Digite o salário: '))
ano = 1995
ano_atual = int(input('Digite o ano em que estamos: '))
aumento = 1.5/100

while ano <= ano_atual:
  salario += salario * aumento
  aumento *=2
  ano +=1

print('O salario atual do funcionário em {} é R$ {:.2f}'.format(ano_atual, salario))

"""5. Faça um programa que leia e valide as seguintes informações:

 Nome: maior que 3 caracteres;

 Idade: entre 0 e 150;

 Salário: maior que zero;

 Sexo: 'f' ou 'm';

 Estado Civil: 's', 'c', 'v', 'd';:

"""

nome = input('Digite um nome: ')

while len(nome) <=3:
  nome = input(" O nome precisa ter mais de 3 caracteres, digite o seu nome novamente: ")

idade = int(input('Digite a sua idade: '))
while idade < 0 and idade < 150:
  idade = int(input('Idade inválida, digite sua idade novamente: '))

salario = int(input('Digite o seu salario: '))
while salario <=0:
  salario = float('Salário inválido! Digite um número maior que 0: ')

sexo = input('Digite o seu sexo (f, m): ')
while sexo != 'f' and sexo != 'm':
  sexo = input('Digite seu sexo novamente')

estado_civil = input('Digite o seu estado cívil (c,s,d,v): ')
while estado_civil != 'c' and estado_civil != 's' and estado_civil != 'd' and estado_civil != 'v':
  estado_civil = input('Digite um estado civil válido')

print('Parabéns! Cadastro feito com sucesso')

"""6. Supondo que a população de um país A seja da ordem de 80000 habitantes com
uma taxa anual de crescimento de 3% e que a população de B seja 200000
habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e
escreva o número de anos necessários para que a população do país A ultrapasse
ou iguale a população do país B, mantidas as taxas de crescimento.
"""

populacao_A = 80000
taxa_crescimento_A = 0.03

populacao_B =20000
taxa_crescimento_B = 0.015

anos = 0

while populacao_A <= populacao_B:
  populacao_A *= (1+ taxa_crescimento_A)
  populacao_A *= (1 + taxa_crescimento_B)
  anos +=1

print('Serão necessários {} anos para que a população do país A ultrapasse ou iguale a população do país B'.format(anos))

"""7. Faça um programa que calcule o fatorial de um número inteiro fornecido pelo
usuário. Ex.: 5!=5.4.3.2.1=120
"""

numero = int(input('Digite um número inteiro para calcular o fatorial: '))

fatorial = 1

i = 1

while i <= numero:
  fatorial *= i
  i+=1

print('O fatorial de {} é {}'.format(numero, fatorial))

"""8. Faça um programa que solicite ao usuário números indefinidamente até que ele
digite 0. Em seguida, o programa deve imprimir a média dos números digitados
"""

soma = 0
contador = 0

while True:
  numero = float(input('Digite um número (ou 0 para sair): '))

  if numero == 0:
    break

  soma += numero
  contador += 1

  if contador != 0:
    media = soma /contador
    print('A média dos números digitados é: {}'.format(media))

  else:
    print('Nenhum numero foi digitado!')

"""9. A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,...Faça um programa capaz de gerar a série até o n−ésimo termo."""

n = int(input("Digite o valor de 'n' para obter a série de Fibonacci até o n-ésimo termo: "))

a, b = 1, 1

fibonacci_series = [a, b]

while len(fibonacci_series) < n:

    next_term = a + b

    fibonacci_series.append(next_term)

    a, b = b, next_term

print("A série de Fibonacci até o {}-ésimo termo é:".format(n))
print(fibonacci_series)

"""10. Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e agora possui uma loja de conveniências. Faça um programa que implemente uma caixa registradora rudimentar.


 O programa deverá receber um número desconhecido de valores referentes aos preços das mercadorias. Um valor zero deve ser informado pelo operador para indicar o final da compra.


 O programa deve então mostrar o total da compra e perguntar o valor em dinheiro que o cliente forneceu, para então calcular e mostrar o valor do troco. Após esta operação, o programa deverá voltar ao ponto inicial, para registrar a próxima compra.


 A saída deve ser conforme o exemplo abaixo:

 Lojas Tabajara

 Produto 1: R$ 2.20

 Produto 2: R$ 5.80

 Produto 3: R$ 0

 Total: R$ 9.00

 Dinheiro: R$ 20.00

 Troco: R$ 11.00
"""

print("Lojas Tabajara")

while True:
    total = 0
    quantidade_produtos = 0

    while True:
        preco_produto = float(input(f"Produto {quantidade_produtos + 1}: R$ "))
        if preco_produto == 0:
            break
        total += preco_produto
        quantidade_produtos += 1

    print(f"Total: R$ {total:.2f}")

    dinheiro_cliente = float(input("Dinheiro: R$ "))
    troco = dinheiro_cliente - total

    print(f"Troco: R$ {troco:.2f}")

    opcao = input("Digite 'S' para registrar outra compra ou qualquer outra tecla para sair: ")
    if opcao.upper() != 'S':
        break

"""11. O cardápio de uma lanchonete é o seguinte: Especificação Código Preço
 Cachorro Quente 100
R$ 1,20 R$ 1,30
R$ 1,50 R$ 1,20
R$ 1,30 R$ 1,00
 Bauru Simples
 Bauru com ovo
 Hambúrguer
 Cheeseburguer
 Refrigerante 105
101 102
103 104
Faça um programa que leia o código dos itens pedidos e as quantidades desejadas. Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.
"""

cardapio = {
    100: {'nome': 'Cachorro Quente', 'precos': [1.20, 1.30, 1.50, 1.30, 1.00]},
    101: {'nome': 'Bauru Simples', 'precos': [1.10, 1.30, 1.50, 1.20, 1.10]},
    102: {'nome': 'Bauru com ovo', 'precos': [1.30, 1.50, 1.70, 1.50, 1.30]},
    103: {'nome': 'Hambúrguer', 'precos': [1.20, 1.40, 1.60, 1.40, 1.20]},
    104: {'nome': 'Cheeseburguer', 'precos': [1.30, 1.50, 1.70, 1.50, 1.30]},
    105: {'nome': 'Refrigerante', 'precos': [1.00, 1.20, 1.50, 1.20, 1.00]}
}

print("Bem-vindo à Lanchonete!")
total_pedido = 0

while True:
    codigo = int(input("Digite o código do item desejado (ou 0 para encerrar o pedido): "))
    if codigo == 0:
        break

    if codigo not in cardapio:
        print("Código de item inválido. Por favor, tente novamente.")
        continue

    quantidade = int(input(f"Digite a quantidade de '{cardapio[codigo]['nome']}': "))

    preco_unitario = cardapio[codigo]['precos'][quantidade - 1]
    subtotal = preco_unitario * quantidade
    total_pedido += subtotal

    print(f"Subtotal para '{cardapio[codigo]['nome']}': R$ {subtotal:.2f}")

print(f"Total do pedido: R$ {total_pedido:.2f}")
print("Obrigado pela preferência!")

"""12.Em uma eleição presidencial existem quatro candidatos. Os votos são informados por meio de código.
Os códigos utilizados são:
 1, 2, 3, 4 - Votos para os respectivos candidatos
 (você deve montar a tabela ex: 1 - Jose/ 2- João/etc)
 5 - Voto Nulo
 6 - Voto em Branco
Faça um programa que calcule e mostre:
 O total de votos para cada candidato;
 O total de votos nulos;
 O total de votos em branco;
 A percentagem de votos nulos sobre o total de votos;
 A percentagem de votos em branco sobre o total de votos.
Para finalizar o conjunto de votos tem-se o valor zero.
"""

print("Eleição Presidencial")
print("Candidatos:")
print("1 - José")
print("2 - João")
print("3 - Maria")
print("4 - Ana")
print("5 - Voto Nulo")
print("6 - Voto em Branco")


votos_candidatos = [0, 0, 0, 0]
votos_nulos = 0
votos_em_branco = 0
total_votos = 0

while True:
    voto = int(input("Digite o código do candidato (ou 0 para encerrar): "))
    if voto == 0:
        break

    if voto >= 1 and voto <= 4:
        votos_candidatos[voto - 1] += 1
    elif voto == 5:
        votos_nulos += 1
    elif voto == 6:
        votos_em_branco += 1
    else:
        print("Código inválido. Voto não será contabilizado.")

    total_votos += 1

percentual_nulos = (votos_nulos / total_votos) * 100 if total_votos != 0 else 0
percentual_branco = (votos_em_branco / total_votos) * 100 if total_votos != 0 else 0

print("\nResultados da Eleição:")
for i, votos in enumerate(votos_candidatos):
    print(f"Total de votos para o Candidato {i+1}: {votos}")

print(f"Total de votos nulos: {votos_nulos}")
print(f"Total de votos em branco: {votos_em_branco}")
print(f"Percentual de votos nulos sobre o total de votos: {percentual_nulos:.2f}%")
print(f"Percentual de votos em branco sobre o total de votos: {percentual_branco:.2f}%")